In [ ]:
"""Create a 8x8 matrix and fill it with a checkerboard pattern [5 Points]"""
import numpy as np
a = np.zeros((8,8))
a[::, 1::2]=1
print(a.astype(int))

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


In [ ]:
"""Create a checkerboard 8x8 matrix using the tile function """
import numpy as np
x = np.empty((8, 8))
v = np.array([0,1,0,1,0,1,0,1])
vv = np.tile(v, (8,1))
print(vv)


[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


In [ ]:
"""(Indexing and Slicing arrays) Create an array containing the values 1–15, reshape it into a 3-
by-5 array, then use indexing and slicing techniques to perform each of the following operations:
1. Select row 2.
2. Select column 5.
3. Select rows 0 and 1.
4. Select columns 2–4.
5. Select the element that is in row 1 and column 4.
6. Select all elements from rows 1 and 2 that are in columns 0, 2 and 4.
"""
import numpy as np
a= np.arange(1,16).reshape(3,5)
print(a,"\n\n Select Row 2: \n")
print(a[1::2],"\n\n Select column 4: \n")
print(a[:, 3].reshape(3,1),"\n\n Select rows 0-1:\n")
print(a[0:2,:], "\n\n Select Columns 2-4  \n")
print(a[:,1:4], "\n\n Select the element that is in row 1 and column 4: \n")
print(a[0,3],"\n\n select all elements from rows 1 and 2 that are in columns 0,2,4")
print(a[1:3,[0,2,4]])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]] 

 Select Row 2: 

[[ 6  7  8  9 10]] 

 Select column 4: 

[[ 4]
 [ 9]
 [14]] 

 Select rows 0-1:

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

 Select Columns 2-4  

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]] 

 Select the element that is in row 1 and column 4: 

4 

 select all elements from rows 1 and 2 that are in columns 0,2,4
[[ 6  8 10]
 [11 13 15]]


In [ ]:
"""array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])
1. Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2.
2. Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right of array1.
3. Use vertical stacking with two copies of array4 to create a 4-by-4 array5.
4. Use horizontal stacking with two copies of array3 to create a 4-by-4 array6.
"""
import numpy as np
array1 = np.array([[0, 1], [2, 3]])
array2 = np.array([[4, 5], [6, 7]])
print("Array1 \n",array1)
print("Array2 \n",array2)
print(" \nUse vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2\n")
array3 = np.vstack((array1,array2))
print("array 3\n", array3)
print("\n Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right of array1.\n")
array4=np.hstack((array1,array2))
print("array 4\n", array4)
print("\n Use vertical stacking with two copies of array4 to create a 4-by-4 array5\n")
array5 = np.tile(array4,(2,1))
print("array 5 \n", array5)
print("\nUse horizontal stacking with two copies of array3 to create a 4-by-4 array6.\n")
array6 = np.tile(array3,(1,2))
print("array 6\n",array6)
#The last two arrays are naturally 4x4 due to the nature of they are stacked, so I decided not to use a reshape opperation

Array1 
 [[0 1]
 [2 3]]
Array2 
 [[4 5]
 [6 7]]
 
Use vertical stacking to create the 4-by-2 array named array3 with array1 stacked on top of array2

array 3
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

 Use horizontal stacking to create the 2-by-4 array named array4 with array2 to the right of array1.

array 4
 [[0 1 4 5]
 [2 3 6 7]]

 Use vertical stacking with two copies of array4 to create a 4-by-4 array5

array 5 
 [[0 1 4 5]
 [2 3 6 7]
 [0 1 4 5]
 [2 3 6 7]]

Use horizontal stacking with two copies of array3 to create a 4-by-4 array6.

array 6
 [[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]]
